name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'your local repo branch'
        required: true
        default: 21.02
        type: choice
        options:
        - master
        - 22.03
        - 21.02

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [bcm53xx-generic, ramips-mt7621, rockchip-armv8, sunxi-cortexa7, x86-64, x86-generic]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ./scripts/00_init.sh build_env

    - name: Variable
      id: var
      run: |
        case ${{ github.event.inputs.branch }} in
          master)
            _branch=${{ github.event.inputs.branch }}
            _name_tag=snapshot-r$(date +%g.%j)
            _prerelease=true
            ;;
          22.03)
            _branch=v${{ github.event.inputs.branch }}.0-rc1
            _name_tag=$_branch
            _prerelease=true
            ;;
          21.02)
            _branch=v${{ github.event.inputs.branch }}.3
            _name_tag=$_branch
            _prerelease=false
            ;;
          *)
            echo "Can't get local/upstream's branch/tags"
            ;;
        esac
        case ${{ matrix.target }} in
          bcm53xx-generic)  _device=k3                ;;
          ramips-mt7621)    _device=k2p               ;;
          rockchip-armv8)   _device=r2c-r2s           ;;
          sunxi-cortexa7)   _device=zeropi            ;;
          x86-64)           _device=x86-64            ;;
          x86-generic)      _device=x86-generic       ;;
          *)                echo "wrong devices"      ;;
        esac
        echo ::set-output name=remote-branch::$_branch
        echo ::set-output name=release_tag::$_name_tag
        echo ::set-output name=release::$_prerelease
        echo ::set-output name=device::$_device

    - name: Prepare Openwrt
      run: |
        ./scripts/00_init.sh immortalwrt

    - name: Clone OpenWrt
      run: |
        git clone -b ${{ steps.var.outputs.remote-branch }} --depth 1 --single-branch https://github.com/openwrt/openwrt

    - name: Feeds update
      run: |
        ./scripts/00_init.sh feeds

    - name: Customize Packages
      working-directory: ./openwrt
      run: |
        cp -L ../scripts/${{ steps.var.outputs.device }}_customization.sh .
        /bin/bash ${{ steps.var.outputs.device }}_customization.sh
        cp ../scripts/01_customize_packages.sh .
        /bin/bash 01_customize_packages.sh

    - name: Convert Translation
      working-directory: ./openwrt
      run: |
        cp ../scripts/02_convert_translation.sh .
        /bin/bash 02_convert_translation.sh

    - name: Add ACL
      working-directory: ./openwrt
      run: |
        cp ../scripts/03_create_acl_for_luci.sh .
        /bin/bash 03_create_acl_for_luci.sh -a

    - name: Get cache toolchain
      uses: klever1988/cachewrtbuild@test
      with:
        ccache: 'true'
        prefix: ${{ github.workspace }}/openwrt
        mixkey: ${{ matrix.target }}-

    - name: Make Config
      working-directory: ./openwrt
      run: |
        cp ../config/${{ steps.var.outputs.device }}_defconfig .config
        make defconfig

    - name: Make Download
      working-directory: ./openwrt
      run: |
        make download -j`nproc`

    - name: Compile OpenWrt
      working-directory: ./openwrt
      run: |
        make -j`nproc` || make -j1 V=s

    - name: Assemble Artifact
      run: |
        _artifact_path=${{ matrix.target }}
        rm -rf ./artifact
        ls openwrt/bin/targets/${_artifact_path/-//}/
        mv openwrt/bin/targets/${_artifact_path/-//}/ ./artifact
        pushd artifact
        cat config.buildinfo
        rm -rf packages *.buildinfo *.json *.manifest *kernel.bin *-rootfs.* sha256sums
        popd

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.var.outputs.release_tag }}
        path: artifact/*

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: ${{ steps.var.outputs.release }}
        tag_name: ${{ steps.var.outputs.release_tag }}
        files: artifact/*
